name: eventpix_mobile
description: "Mobile app that extracts schedules from images and automatically registers them to a calendar."
publish_to: 'none' 

version: 0.0.1+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/icon/logo_adaptive.png
    - assets/icon/logo_name.png
    - assets/icon/logo_square.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/logo_square.png"
  adaptive_icon_foreground: "assets/icon/logo_adaptive.png"
  adaptive_icon_background: "#FF6700"
