name: CI (Flutter)
on: pull_request

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          architecture: x64
        
      - name: Install Dependencies
        run: |
          flutter pub get

      - name: Format Check
        run: |
          dart format --set-exit-if-changed .

      - name: Lint
        run: |
          flutter analyze

      - name: Test
        run: |
          flutter test
